### ISSUE TITLE
Plugin is not loading

### ISSUE THREAD

**Issue by surfrock66** [DmitryRendov/JDynmapGriefPrevention#7] opened 2021-02-02 17:27 UTC
Minecraft 1.16.5 server using paper v455.  I have Dynmap-3.1-beta6-spigot.jar and JDynmapGriefPrevention-3.6.1.jar from this repo. I have GriefPrevention.16.17.1.jar.

When I load my server or reload the plugins I get the following:

```
[09:22:24 INFO]: [JDynmapGriefPrevention] Enabling JDynmapGriefPrevention v3.6.1
[09:22:24 INFO]: [JDynmapGriefPrevention] Initializing...
[09:22:24 ERROR]: Error occurred while enabling JDynmapGriefPrevention v3.6.1 (Is it up to date?)
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key config.claims.name
        at java.util.ResourceBundle.getObject(ResourceBundle.java:564) ~[?:?]
        at java.util.ResourceBundle.getString(ResourceBundle.java:521) ~[?:?]
        at jahan.khan.JDynmapGriefPrevention.JDynmapGriefPrevention.activate(JDynmapGriefPrevention.java:1431) ~[?:?]
        at jahan.khan.JDynmapGriefPrevention.JDynmapGriefPrevention.onEnable(JDynmapGriefPrevention.java:1374) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-455]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-455]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-455]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-455]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-455]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:945) ~[patched_1.16.5.jar:git-Paper-455]
        at org.bukkit.Bukkit.reload(Bukkit.java:708) ~[patched_1.16.5.jar:git-Paper-455]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.16.5.jar:git-Paper-455]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-455]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.5.jar:git-Paper-455]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:769) ~[patched_1.16.5.jar:git-Paper-455]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411) ~[patched_1.16.5.jar:git-Paper-455]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.5.jar:git-Paper-455]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.5.jar:git-Paper-455]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-455]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-455]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[09:22:24 INFO]: [JDynmapGriefPrevention] Disabling JDynmapGriefPrevention v3.6.1
[09:22:24 INFO]: [JDynmapGriefPrevention] Plugin JDynMapGriefPrevention disabled
```

**Comment by DmitryRendov** [comment] 2021-05-05 09:29
@surfrock66  what java version do you use?
I'm unable to reproduce the issue with given setup and Java8. Here is my server log with no exceptions https://pastebin.com/Ja2ex8M8

**Comment by surfrock66** [comment] 2021-05-05 15:52
openjdk 11.0.11 2021-04-20

**Comment by DmitryRendov** [comment] 2021-05-06 06:40
isnt reproducing  on Oracle Java 11 as well https://pastebin.com/vAgMGKYJ
will have a look at openjdk later, though I don't think it is a reason.

Coudl you please try to backup and remove the JDynmapGriefPrevention folder

**Comment by surfrock66** [comment] 2021-05-06 16:03
I actually switched to a different plugin, but I still have the disabled jar for this, next time i do a server reboot I'll try it.

**Comment by soliddanii** [comment] 2021-09-25 09:58
I know this is old, but the same happened to me and I want to leave here the solution in case someone finds this in the future.

The problem is the language file is missing some keys. The error points to "config.claims.name" but in my case it lacked some more. The simpler solution is to delete "Messages_en.properties" (or the locale you are using) and simply let it regenerate. In case you made your own language just make a backup and compare the diff later so you know what to edit.

**Comment by DmitryRendov** [comment] 2022-12-27 09:33
I will close this one. Let me know if the issue still exists.

**Closed as completed by DmitryRendov** 2022-12-27 09:33 UTC
